<?php

namespace App\Console\Commands;

use App\Jobs\ProcessSoundUpload;
use App\Models\Category;
use App\Models\License;
use App\Models\Tag;
use App\Models\User;
use App\Services\AudioProcessor;
use App\Services\SoundImporter;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Process;
use Illuminate\Support\Str;

/**
 * Fills the catalogue with synthesised audio so the site can be tested with
 * volume: pagination, search relevance, filters, category counts.
 *
 * These are real audio files generated by ffmpeg, not fixtures — they get
 * processed by the same pipeline as a genuine upload, so timings and
 * waveforms are realistic.
 */
class GenerateDemoSoundsCommand extends Command
{
    protected $signature = 'sounds:demo
                            {count=40 : How many to generate}
                            {--publish : Publish them straight away instead of leaving them in review}
                            {--fresh : Delete previously generated demo sounds first}';

    protected $description = 'Generate synthetic sounds to test the catalogue with volume';

    /**
     * Each recipe is an ffmpeg filter plus the vocabulary used to name it.
     * The names matter: they are what the search gets tested against.
     */
    protected array $recipes = [
        [
            'category' => 'nature',
            'filter' => 'anoisesrc=c=pink:d=%.1f,highpass=f=200,lowpass=f=6000',
            'words' => ['Rain On Window', 'Heavy Downpour', 'Distant Thunder', 'Forest Wind', 'Ocean Waves', 'Waterfall Rumble', 'Light Drizzle', 'Storm Approaching'],
            'tags' => ['rain', 'weather', 'ambience', 'nature', 'loop'],
        ],
        [
            'category' => 'sci-fi',
            'filter' => 'sine=frequency=%d:duration=%.1f,vibrato=f=8:d=0.6,aecho=0.8:0.9:60:0.4',
            'words' => ['Laser Charge Up', 'Teleport Beam', 'Robot Servo Turn', 'Spaceship Pass By', 'Energy Shield Hum', 'Plasma Discharge', 'Scanner Sweep', 'Warp Engage'],
            'tags' => ['sci-fi', 'laser', 'futuristic', 'synth'],
        ],
        [
            'category' => 'interface',
            'filter' => 'sine=frequency=%d:duration=%.1f,afade=t=out:st=0.05:d=0.2',
            'words' => ['UI Click Soft', 'Notification Ping', 'Menu Select', 'Error Buzz', 'Toggle Switch', 'Message Received', 'Button Tap', 'Success Chime'],
            'tags' => ['ui', 'interface', 'click', 'notification', 'short'],
        ],
        [
            'category' => 'cinematic',
            'filter' => 'anoisesrc=c=brown:d=%.1f,lowpass=f=400,afade=t=in:st=0:d=1',
            'words' => ['Cinematic Impact Deep', 'Tension Riser', 'Trailer Boom', 'Sub Drop', 'Dramatic Whoosh', 'Epic Hit', 'Dark Drone', 'Suspense Swell'],
            'tags' => ['cinematic', 'impact', 'trailer', 'dramatic'],
        ],
        [
            'category' => 'foley',
            'filter' => 'anoisesrc=c=white:d=%.1f,highpass=f=1200,tremolo=f=%d:d=0.9',
            'words' => ['Wooden Door Creak', 'Footsteps On Gravel', 'Paper Rustle', 'Glass Clink', 'Cloth Movement', 'Keys Jingle', 'Box Sliding', 'Metal Scrape'],
            'tags' => ['foley', 'texture', 'organic'],
        ],
        [
            'category' => 'horror',
            'filter' => 'sine=frequency=%d:duration=%.1f,tremolo=f=3:d=0.8,aecho=0.9:0.9:1000:0.5',
            'words' => ['Ghostly Whisper', 'Creaking Floorboard', 'Distant Scream', 'Eerie Drone', 'Heartbeat Slow', 'Chains Dragging', 'Breath In Dark', 'Unsettling Tone'],
            'tags' => ['horror', 'scary', 'tension', 'dark'],
        ],
    ];

    public function handle(AudioProcessor $audio, SoundImporter $importer): int
    {
        if (! $audio->isAvailable()) {
            $this->error('ffmpeg is required. Run: brew install ffmpeg');

            return self::FAILURE;
        }

        $user = User::where('role', User::ROLE_ADMIN)->first();

        if (! $user) {
            $this->error('No admin user found. Run: php artisan db:seed');

            return self::FAILURE;
        }

        if ($this->option('fresh')) {
            $deleted = \App\Models\Sound::where('description', 'like', '%[demo]%')->get();
            $deleted->each->forceDelete();
            $this->warn("Removed {$deleted->count()} previous demo sound(s).");
        }

        $license = License::where('slug', 'dbelo-standard')->first();
        $count = max(1, (int) $this->argument('count'));

        $this->info("Generating {$count} demo sound(s)…");
        $bar = $this->output->createProgressBar($count);

        $tempDir = sys_get_temp_dir().'/dbelo-demo';
        @mkdir($tempDir, 0755, true);

        for ($i = 0; $i < $count; $i++) {
            $recipe = $this->recipes[$i % count($this->recipes)];
            $title = $recipe['words'][intdiv($i, count($this->recipes)) % count($recipe['words'])];

            // Repeats get a variant suffix so titles stay distinguishable
            // once the count exceeds the vocabulary.
            $round = intdiv($i, count($this->recipes) * count($recipe['words']));
            if ($round > 0) {
                $title .= ' '.chr(65 + $round);
            }

            $duration = $this->durationFor($recipe['category'], $i);
            $file = $tempDir.'/'.Str::slug($title).'-'.$i.'.wav';

            if (! $this->synthesise($recipe['filter'], $duration, $i, $file)) {
                $bar->advance();

                continue;
            }

            $category = Category::where('slug', $recipe['category'])->first();

            $sound = $importer->import($file, basename($file), $user, $category, $license, [
                'title' => $title,
                'description' => 'Synthesised placeholder for testing. [demo]',
                'is_premium' => $i % 5 === 0,
                'is_loopable' => $duration > 8,
            ]);

            foreach (array_slice($recipe['tags'], 0, 4) as $name) {
                $tag = Tag::firstOrCreate(['slug' => Str::slug($name)], ['name' => $name]);
                $sound->tags()->attach($tag->id);
            }

            ProcessSoundUpload::dispatchSync($sound);
            $sound->refresh();

            if ($this->option('publish') && $sound->status === 'pending') {
                $sound->update([
                    'status' => 'published',
                    'published_at' => now()->subDays(rand(0, 60)),
                    'downloads_count' => rand(0, 400),
                ]);
            }

            @unlink($file);
            $bar->advance();
        }

        $bar->finish();
        $this->newLine(2);

        $this->info($this->option('publish')
            ? 'Done. The catalogue is live at /sounds'
            : 'Done. Approve them at /moderate, or re-run with --publish.');

        if (config('scout.driver') === 'meilisearch') {
            $this->comment('Reindex if search looks stale: php artisan scout:import "App\Models\Sound"');
        }

        return self::SUCCESS;
    }

    /**
     * Realistic spread of lengths so the duration filters have something to
     * actually filter.
     */
    protected function durationFor(string $category, int $i): float
    {
        return match ($category) {
            'interface' => round(0.3 + ($i % 3) * 0.25, 1),
            'foley' => round(1.5 + ($i % 4) * 1.2, 1),
            'cinematic' => round(4 + ($i % 3) * 2.5, 1),
            'horror' => round(6 + ($i % 4) * 3, 1),
            default => round(12 + ($i % 5) * 9, 1),
        };
    }

    protected function synthesise(string $filter, float $duration, int $seed, string $output): bool
    {
        $frequency = 120 + (($seed * 37) % 900);

        // Recipes take either (duration) or (frequency, duration) depending
        // on the filter, so the argument count is worked out from the format.
        $filterString = substr_count($filter, '%') > 1
            ? sprintf($filter, $frequency, $duration)
            : sprintf($filter, $duration);

        $result = Process::timeout(60)->run([
            'ffmpeg', '-y', '-v', 'quiet',
            '-f', 'lavfi',
            '-i', $filterString,
            '-t', (string) $duration,
            '-ar', '48000',
            '-ac', '2',
            '-c:a', 'pcm_s24le',
            $output,
        ]);

        if (! $result->successful()) {
            $this->newLine();
            $this->warn('ffmpeg failed on one recipe, skipped.');

            return false;
        }

        return true;
    }
}
